X delete a single profile
X delete all profiles
X edit field in given profile
Q prompt for ssh passphrase
X change prompt of Password: to explain what it's for
Q edit field in given auth
X Password: doesn't make sense (changed to Config Encryption Password:)
X bin/rho auth add prints None at the end for no reason
Q ports not validated for valid values i.e. -1 or 333333 is accepted.
Q add ssh port that worked to output report
* rho scan --range needs a decryption password (which it probably shouldn't)
Q --profile is missing from rho scan
Q profile add with --auth=[nonexistent auth] gives traceback, should just print 'auth doesn't exist' - same with nonexistent ssh keyfile, etc
X profile add --ip doesn't work
Q rho scan --help should say "profile" on the usage line. 
Q rho scan: you can scan using a profile and at the same time specify a
  --range on the command line.. the scan goes into loops
X include ip or hostname in connection failed before report is listed

Q dumpconfig contains a stanza called "groups". For consistency reasons we
  think it should be called "profiles". 

Q profile add --range:  the range string should be validated for format at  profile creation

Q adding a duplicate profile, causes traceback

X rho scan --ip doesnt work
(--ip removed)

X profile clear --name does not work 

Q Can not add a private RSA key to authentication

Q no dsa keys - can add using 'auth add' but then scan fails with "10.10.77.239,,,,,,,,,,connection failed using auth class: myvm not a valid RSA private key file"
X * "connection failed using auth class: mypw Authentication failed." or "timed out". Need to include what IP this was.

* we write stuff to stdout that shoudl be stderr, needs clean up

Q* if we try to add/edit a profile and give it an auth that doesn't exist, we 
Q  get an exception, and then the config is busted.
Q Profile f11-bogus-multiauth-multiport edited
Q [adrian@alikins rho]$ rho dumpconfig
Q Traceback (most recent call last):
Q  File "/home/adrian/src/rho/bin/rho", line 22, in <module>
Q   CLI().main()
Q  File "/home/adrian/src/rho/src/rho/cli.py", line 95, in main
Q    cmd.main()
Q  File "/home/adrian/src/rho/src/rho/clicommands.py", line 133, in main
Q    self.config = self._read_config(self.options.config, self.passphrase)
Q  File "/home/adrian/src/rho/src/rho/clicommands.py", line 98, in _read_config
Q    return config.ConfigBuilder().build_config(confstr)
Q  File "/home/adrian/src/rho/src/rho/config.py", line 289, in build_config
Q    config = Config(auths=creds, profiles=profiles)
Q  File "/home/adrian/src/rho/src/rho/config.py", line 93, in __init__
Q    self.add_profile(profile)
Q  File "/home/adrian/src/rho/src/rho/config.py", line 134, in add_profile
Q    c)
Q rho.config.ConfigError: No such credentials: rsa_key


Q* if we try to "rho profile edit" a profile that doesnt exist:
Q Traceback (most recent call last):
Q  File "/home/adrian/src/rho/bin/rho", line 22, in <module>
Q    CLI().main()
Q  File "/home/adrian/src/rho/src/rho/cli.py", line 95, in main
Q    cmd.main()
Q  File "/home/adrian/src/rho/src/rho/clicommands.py", line 136, in main
Q    self._do_command()
Q  File "/home/adrian/src/rho/src/rho/clicommands.py", line 461, in _do_command
Q    g.ranges = self.options.ranges
Q AttributeError: 'NoneType' object has no attribute 'ranges'

===============
X = fixed
Q = dev says it's fixed but noone else has tested it, hahahahaha
A = Ack (kidding...)
=================

-------------------
NOT A BUG (one command uses --config the other doesn't, this
results in 2 different configs being used)

X auth configs using ssh keys not listed w/ auth show

[whayutin@thinkdoe rho]$ bin/rho auth add --name=sshKey
--file=/home/whayutin/workspace/rho/id_rsa --config=$PWD/sshConfig
--username=bad --password=bad
Config Encryption Password:
The auth name sshKey already exists
[whayutin@thinkdoe rho]$ bin/rho auth show
Config Encryption Password:
{'username': 'whayutin', 'password': 'passw0rd', 'type': 'ssh', 'name':
'default'}
{'username': 'whayutin', 'password': 'b0rder', 'type': 'ssh', 'name':
'whayutin'}
[whayutin@thinkdoe rho]$

------------------



profile list, and profile show --name"" seem to list the same output.  We may
want to just show profile names when "rho profile list" is called"
[whayutin@thinkdoe rho]$ rho profile show --name whayutin.rdu.redhat.com
Config Encryption Password:
{'auths': ['keys'], 'range': ['whayutin.rdu.redhat.com'], 'name':
'whayutin.rdu.redhat.com', 'ports': [22]}

[whayutin@thinkdoe rho]$ rho profile list
Config Encryption Password:
{'auths': ['keys'], 'range': ['whayutin.rdu.redhat.com'], 'name':
'whayutin.rdu.redhat.com', 'ports': [22]}
[whayutin@thinkdoe rho]$ 



Q -------------------------------------------------------
Q
Q add an auth that is only using an sshkey w/ a passphrase
Q add a profile that uses the auth.  run a scan.. rho prompts for a password,
Q but its really prompting for the ssh passphrase.  
Q
Q Please change the txt for passwd prompt to say passphrase
Q Q-------------------------------------------------------



Q -------------------------
Q clarify ssh error... getting similar error for ssh not running ,and bad
Q passphrase
Q Config Encryption Password:
Q 10.11.228.65,,,,,,,,,,,,,,,,,no ssh
Q --------------------------



Q * if we try to specify an auth at scantime:

Fixed now, shouldn't be able to specify an auth and a profile at the same
time, the profile already has auths associated with it.

Q [thesteve04@cinemashow rho]$ rho scan notontarget --auth=dog8code
Q Config Encryption Password:
Q Exception: local variable 'ssh' referenced before assignment

Q (<type 'exceptions.UnboundLocalError'>, UnboundLocalError("local variable 'ssh' referenced before assignment",), <traceback object at 0x96a139c>)
Q   File "build/bdist.linux-i686/egg/rho/my_sshpt.py", line 276, in attemptConnection
Q     ssh = paramikoConnect(ssh_job)
Q   File "build/bdist.linux-i686/egg/rho/my_sshpt.py", line 258, in paramikoConnect
Q     return ssh
Q None
Q   File "build/bdist.linux-i686/egg/rho/my_sshpt.py", line 64, in run
Q     self.report.add(queueObj)
Q   File "build/bdist.linux-i686/egg/rho/scanner.py", line 50, in add
Q     'auth.type': ssh_job.auth.type,



--------------------------------------------------
FIXED
Q Add a profile w/ a range but no auth...

[whayutin@thinkdoe .ssh]$ rho profile add --name=busted1
--range=whayutin.rdu.redhat.com 
Config Encryption Password:
[whayutin@thinkdoe .ssh]$ rho scan --profile=busted1
Config Encryption Password:
Exception: local variable 'ssh' referenced before assignment

(<type 'exceptions.UnboundLocalError'>, UnboundLocalError("local variable
'ssh' referenced before assignment",), <traceback object at 0x9b995a4>)
  File "/home/whayutin/workspace/rho/src/rho/ssh_queue.py", line 308, in
attemptConnection
    ssh = paramikoConnect(ssh_job)
  File "/home/whayutin/workspace/rho/src/rho/ssh_queue.py", line 290, in
paramikoConnect
    return ssh
None
10.11.228.65,,,,,,,,,,,,,,,,,no ssh



-----------------------------------------------------



Profile edit, lame bug
If you make no edits to a profile, the command return should not say the
profile was edited

[whayutin@thinkdoe .ssh]$ rho profile edit --name=busted1 
Config Encryption Password:
Profile busted1 edited
[whayutin@thinkdoe .ssh]$ 

Not sure if this is worth fixing or not. - dgoodwin



-----------------------------------------------------



Q * if user adds malformed range, python trace occurs:
Q [thesteve04@cinemashow rho]$ rho profile add --name=hax0r --auth=redhat
Q --range=10.10.76.0/24,10.16.76.0/24
Q  Config Encryption Password:
Q [thesteve04@cinemashow rho]$ rho profile list
Q  Config Encryption Password:
Q  name          	range                    	ports          	auth
Q  --------------	-------------------------	---------------	----
Qidm           	10.16.76.0/24            	22             
Q hax0r         	10.10.76.0/24,10.16.76.0/24	22             
Q
Q[thesteve04@cinemashow rho]$ rho scan hax0r
QConfig Encryption Password:
QTraceback (most recent call last):
Q  File "/usr/bin/rho", line 5, in <module>
Q    pkg_resources.run_script('rho==0.1', 'rho')
Q  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 448, in
Qrun_script
Q    self.require(requires)[0].run_script(script_name, ns)
Q  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1173, in
Qrun_script
Q    exec script_code in namespace, namespace
Q@  File
Q@"/usr/lib/python2.6/site-packages/rho-0.1-py2.6.egg/EGG-INFO/scripts/rho",
Qline 22, in <module>
Q   
Q    < remove traceback spew>
Q    
Qnetaddr.AddrFormatError: '24,10.16.76.0' is not a supported address format!
Q


---------------------



* trace periodically appears in long scans:

Exception: Channel closed.

(<class 'paramiko.SSHException'>, SSHException('Channel closed.',), <traceback object at 0xb5a1f3ec>)
  File "build/bdist.linux-i686/egg/rho/ssh_queue.py", line 314, in attemptConnection
    executeCommands(transport=ssh, rho_commands=ssh_job.rho_cmds)
  File "build/bdist.linux-i686/egg/rho/ssh_queue.py", line 297, in executeCommands
    stdin, stdout, stderr = transport.exec_command(cmd_string)
  File "/usr/lib/python2.6/site-packages/paramiko/client.py", line 350, in exec_command
    chan.exec_command(command)
  File "/usr/lib/python2.6/site-packages/paramiko/channel.py", line 212, in exec_command
    self._wait_for_event()
  File "/usr/lib/python2.6/site-packages/paramiko/channel.py", line 1077, in _wait_for_event
    raise e
None

(looks to be a parmiko bug... https://bugs.launchpad.net/paramiko/+bug/413850)

Strangely enough these two hosts that are failing are EL4 and EL3. However, I
can scan them locally and do not hit the exception, in both cases we're using
F11...



----------------------------------------
FIXED
Q rho profile clear on a profiles that dont exist..
Q [whayutin@thinkdoe ~]$ rho profile clear --name=DOESNOTEXIST
Q Profile DOESNOTEXIST removed
------------------------------

* --range checks validity of ip's in range, which can fail if given a hostname
* that doesnt resolve (--range doesntexist.example.com, for example)

* "rho scan nonexistent" causes a traceback
