===============
N = new
X = fixed
Q = dev says it's fixed but noone else has tested it, hahahahaha
V = verified
A = Ack (kidding...)
=================

profile list, and profile show --name"" seem to list the same output.  We may
want to just show profile names when "rho profile list" is called"
[whayutin@thinkdoe rho]$ rho profile show --name whayutin.rdu.redhat.com
Config Encryption Password:
{'auths': ['keys'], 'range': ['whayutin.rdu.redhat.com'], 'name':
'whayutin.rdu.redhat.com', 'ports': [22]}

[whayutin@thinkdoe rho]$ rho profile list
Config Encryption Password:
{'auths': ['keys'], 'range': ['whayutin.rdu.redhat.com'], 'name':
'whayutin.rdu.redhat.com', 'ports': [22]}
[whayutin@thinkdoe rho]$ 


* --range checks validity of ip's in range, which can fail if given a hostname
* that doesnt resolve (--range doesntexist.example.com, for example)

n rho auth edit, can not change from ssh_key to just ssh
n edit field in given auth -- so this partially fails (weshay)

n------------------------
n*[test@whayutin .ssh]$ rho profile show --name mymachine
n
nname: mymachine
n    auths:
n        foobar
n   ports:
n        23
n    ranges:
n        auto-jon23.usersys.redhat.com
n[test@whayutin .ssh]$ rho scan mymachine --ports=22
nauto-jon23.usersys.redhat.com,,,,,,,,,,,,,,,,,,,,unable to connect
nntest@whayutin .ssh]$ 
n-----------------------------

n  rho scan: you can scan using a profile and at the same time specify a
n  dumpconfig contains a stanza called "groups". For consistency reasons we
n  think it should be called "profiles". 

nnnnnnnnnnn
10.10.10.300 should throw a number format error.. as numbers can not be > 255
[test@whayutin ~]$ rho profile add --name=range --auth=auto --range=10.10.10.300
[test@whayutin ~]$ rho profile add --name=range --auth=auto1 --range=10.10.10.300/24
Traceback (most recent call last):
  File "/home/test/rho/bin/rho", line 20, in <module>
    CLI().main()
  File "/home/test/rho/src/rho/cli.py", line 95, in main
    cmd.main()
  File "/home/test/rho/src/rho/clicommands.py", line 267, in main
    self._validate_options()
  File "/home/test/rho/src/rho/clicommands.py", line 760, in _validate_options
    self._validate_ranges(self.options.ranges)
  File "/home/test/rho/src/rho/clicommands.py", line 217, in _validate_ranges
    ipr =  rho_ips.RhoIpRange(iprange)
  File "/home/test/rho/src/rho/rho_ips.py", line 79, in __init__
    ret = self.parse_iprange(sub_iprange)
  File "/home/test/rho/src/rho/rho_ips.py", line 130, in parse_iprange
    return self.netaddr.get_network(range_str)
  File "/home/test/rho/src/rho/rho_ips.py", line 33, in get_network
    cidr = netaddr.IP(range_str)
  File "/usr/lib/python2.6/site-packages/netaddr/address.py", line 725, in __init__
    super(IP, self).__init__(addr, addr_type)
  File "/usr/lib/python2.6/site-packages/netaddr/address.py", line 237, in __init__
    self.value = addr
  File "/usr/lib/python2.6/site-packages/netaddr/address.py", line 92, in __set__
    'format!' % value)
netaddr.AddrFormatError: '10.10.10.300' is not a supported address format!
[test@whayutin ~]$ 
nnnnnnnnnnnnnnnn




=========================BUGS THAT NEED QA==================================================



* trace periodically appears in long scans:

Exception: Channel closed.

(<class 'paramiko.SSHException'>, SSHException('Channel closed.',), <traceback object at 0xb5a1f3ec>)
  File "build/bdist.linux-i686/egg/rho/ssh_queue.py", line 314, in attemptConnection
    executeCommands(transport=ssh, rho_commands=ssh_job.rho_cmds)
  File "build/bdist.linux-i686/egg/rho/ssh_queue.py", line 297, in executeCommands
    stdin, stdout, stderr = transport.exec_command(cmd_string)
  File "/usr/lib/python2.6/site-packages/paramiko/client.py", line 350, in exec_command
    chan.exec_command(command)
  File "/usr/lib/python2.6/site-packages/paramiko/channel.py", line 212, in exec_command
    self._wait_for_event()
  File "/usr/lib/python2.6/site-packages/paramiko/channel.py", line 1077, in _wait_for_event
    raise e
None

(looks to be a parmiko bug... https://bugs.launchpad.net/paramiko/+bug/413850)

Strangely enough these two hosts that are failing are EL4 and EL3. However, I
can scan them locally and do not hit the exception, in both cases we're using
F11...




====================END==BUGS THAT NEED QA==END================================================
===============================================================================================
=========================BUGS VERIFIED BY QA===================================================

V Can not add a private RSA key to authentication
V prompt for ssh passphrase

V ports not validated for valid values i.e. -1 or 333333 is accepted.  (AUTOMATED, weshay)
[test@whayutin .ssh]$ rho profile edit --name=mymachine --ports=-1
-1 includes an invalid port number. Ports should be between 1 and 65535

V  add ssh port that worked to output report
V --profile is missing from rho scan
V profile add with --auth=[noneVistent auth] gives traceback, should just print 'auth doesn't exist' - same with nonexistent ssh keyfile, etc (automated weshay)
V rho scan --help should say "profile" on the usage line. 
V "rho scan nonexistent" causes a traceback
V profile add --range:  the range string should be validated for format at  profile creation - found bug
V adding a duplicate profile, causes traceback
V  no dsa keys - can add using 'auth add' but then scan fails with "10.10.77.239,,,,,,,,,,connection failed using auth class: myvm not a valid RSA private key file"

V if we try to add/edit a profile and give it an auth that doesn't exist, we 
V  get an exception, and then the config is busted.

V [adrian@alikins rho]$ rho dumpconfig
V Traceback (most recent call last):
V  File "/home/adrian/src/rho/bin/rho", line 22, in <module>
V   CLI().main()
V  File "/home/adrian/src/rho/src/rho/cli.py", line 95, in main
V    cmd.main()
V  File "/home/adrian/src/rho/src/rho/clicommands.py", line 133, in main
V    self.config = self._read_config(self.options.config, self.passphrase)
V  File "/home/adrian/src/rho/src/rho/clicommands.py", line 98, in _read_config
V    return config.ConfigBuilder().build_config(confstr)
V  File "/home/adrian/src/rho/src/rho/config.py", line 289, in build_config
V    config = Config(auths=creds, profiles=profiles)
V  File "/home/adrian/src/rho/src/rho/config.py", line 93, in __init__
V    self.add_profile(profile)
V  File "/home/adrian/src/rho/src/rho/config.py", line 134, in add_profile
V    c)
V rho.config.ConfigError: No such credentials: rsa_key

V * if we try to "rho profile edit" a profile that doesnt exist:
V Traceback (most recent call last):
V  File "/home/adrian/src/rho/bin/rho", line 22, in <module>
V    CLI().main()
V  File "/home/adrian/src/rho/src/rho/cli.py", line 95, in main
V    cmd.main()
V  File "/home/adrian/src/rho/src/rho/clicommands.py", line 136, in main
V    self._do_command()
V  File "/home/adrian/src/rho/src/rho/clicommands.py", line 461, in _do_command
V    g.ranges = self.options.ranges
V AttributeError: 'NoneType' object has no attribute 'ranges'

V -------------------------------------------------------
V
V add an auth that is only using an sshkey w/ a passphrase
V add a profile that uses the auth.  run a scan.. rho prompts for a password,
V but its really prompting for the ssh passphrase.  
V
V Please change the txt for passwd prompt to say passphrase
V V-------------------------------------------------------

V -------------------------
***NOTE HERE** RHO no longer prompts at scan for passphrase
V clarify ssh error... getting similar error for ssh not running ,and bad
V passphrase
V Config Encryption Password:
V 10.11.228.65,,,,,,,,,,,,,,,,,no ssh
V --------------------------

V * if we try to specify an auth at scantime:

Fixed now, shouldn't be able to specify an auth and a profile at the same
time, the profile already has auths associated with it.

V [thesteve04@cinemashow rho]$ rho scan notontarget --auth=dog8code
V Config Encryption Password:
V Exception: local variable 'ssh' referenced before assignment

V (<type 'exceptions.UnboundLocalError'>, UnboundLocalError("local variable 'ssh' referenced before assignment",), <traceback object at 0x96a139c>)
V   File "build/bdist.linux-i686/egg/rho/my_sshpt.py", line 276, in attemptConnection
V     ssh = paramikoConnect(ssh_job)
V   File "build/bdist.linux-i686/egg/rho/my_sshpt.py", line 258, in paramikoConnect
V     return ssh
V None
V   File "build/bdist.linux-i686/egg/rho/my_sshpt.py", line 64, in run
V     self.report.add(queueObj)
V   File "build/bdist.linux-i686/egg/rho/scanner.py", line 50, in add
V     'auth.type': ssh_job.auth.type,

-----------------------------------------------------


V * if user adds malformed range, python trace occurs:
V [thesteve04@cinemashow rho]$ rho profile add --name=hax0r --auth=redhat
V --range=10.10.76.0/24,10.16.76.0/24
V  Config Encryption Password:
V [thesteve04@cinemashow rho]$ rho profile list
V  Config Encryption Password:
V  name          	range                    	ports          	auth
V  --------------	-------------------------	---------------	----
Vidm           	10.16.76.0/24            	22             
V hax0r         	10.10.76.0/24,10.16.76.0/24	22             
V
V[thesteve04@cinemashow rho]$ rho scan hax0r
VConfig Encryption Password:
VTraceback (most recent call last):
V  File "/usr/bin/rho", line 5, in <module>
V    pkg_resources.run_script('rho==0.1', 'rho')
V  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 448, in
Vrun_script
V    self.require(requires)[0].run_script(script_name, ns)
V  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1173, in
Vrun_script
V    exec script_code in namespace, namespace
V@  File
V@"/usr/lib/python2.6/site-packages/rho-0.1-py2.6.egg/EGG-INFO/scripts/rho",
Vline 22, in <module>
V   
V    < remove traceback spew>
V    
Vnetaddr.AddrFormatError: '24,10.16.76.0' is not a supported address format!
V
---------------------

----------------------------------------
FIXED
V rho profile clear on a profiles that dont exist..
V [whayutin@thinkdoe ~]$ rho profile clear --name=DOESNOTEXIST
V Profile DOESNOTEXIST removed
------------------------------


=======================END==BUGS VERIFIED BY QA==END================================================


++++++++++++++++++++++++  Verified by DEV +++++++++++++++++++++++++++++


X delete a single profile
X delete all profiles
X edit field in given profile
X change prompt of Password: to explain what it's for
X Password: doesn't make sense (changed to Config Encryption Password:)
X bin/rho auth add prints None at the end for no reason
* rho scan --range needs a decryption password (which it probably shouldn't)
X profile add --ip doesn't work
  --range on the command line.. the scan goes into loops
X include ip or hostname in connection failed before report is listed
X rho scan --ip doesnt work
(--ip removed)
X profile clear --name does not work 
X * "connection failed using auth class: mypw Authentication failed." or "timed out". Need to include what IP this was.
* we write stuff to stdout that shoudl be stderr, needs clean up

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

NEW BUGS, NOV 17 TESTDAY:
n Traceback when using two auths from 'rho scan': http://wwwapps.rdu.redhat.com/w3xpastebin/pastebin.php?show=15270
n Scanning a range from 'rho scan' non-functional: http://wwwapps.rdu.redhat.com/w3xpastebin/pastebin.php?show=15271
n Deterministic paramiko tracebacks: http://wwwapps.rdu.redhat.com/w3xpastebin/pastebin.php?show=15272